Update Indonesian.properties
yairm210/Unciv pull request #11067
Opened 2024-02-02 08:48 UTC by M792003

2024-02-02 08:51 UTC, M792003 commented
I am X2003, your Discord server member, it's my first time using GitHub. I fixed some translations and translated some words. I am sorry if I made mistakes.

2024-02-03 13:13 UTC, Kensvin28 requested changes

2024-02-03 13:13 UTC, Kensvin28 commented on android/assets/jsons/translations/Indonesian.properties
> +in capital = di ibukota
According to the Indonesian dictionary, ibukota is the informal form of ibu kota, so maybe we should just leave it as is?

2024-02-03 13:13 UTC, Kensvin28 commented on android/assets/jsons/translations/Indonesian.properties
> +in enemy cities = di kota-kota musuj
Should be musuh instead of musuj

2024-02-03 13:13 UTC, Kensvin28 commented on android/assets/jsons/translations/Indonesian.properties
> +Christianity = Kekristenan
For the religions like Christianity, Hinduism, and Buddhism, even though the updated translations are correct in a literal way, here I think it is better to display the religion like what is shown in your identity card like Kristen, Hindu, or Buddha (btw the correct Buddhism uses double d)

2024-02-05 22:19 UTC, merged