Allow stat from battle uniques to also give stockpiles
yairm210/Unciv pull request #12689
Opened 2024-12-21 07:01 UTC by SeventhM

Also add some helpers to GameResource and SubStat to make it easier to work with

2024-12-22 08:09 UTC, yairm210 requested changes

2024-12-22 08:09 UTC, yairm210 commented on core/src/com/unciv/logic/battle/Battle.kt
> +                        "Your [${plunderingUnit.getName()}] plundered [${plunderedAmount}] [${resourceName}] from [${plunderedUnit.getName()}]",
Do we not notify for stat plundering?

2024-12-22 08:09 UTC, yairm210 commented on core/src/com/unciv/logic/battle/Battle.kt
> +                if (resource == null) continue
Add empty lines before and after this segment

2024-12-22 08:09 UTC, yairm210 commented on core/src/com/unciv/logic/battle/Battle.kt
>              if (plunderedUnit.matchesFilter(unique.params[1])) {
Since the body has gotten big with its own nesting, please reverse this if (if !matches() continue)

2024-12-22 08:09 UTC, yairm210 commented on core/src/com/unciv/logic/battle/Battle.kt
> +            if (resource == null) continue
This is repeated at least 3 times, sounds like it should be a function getResource(resourceName)

2024-12-22 18:53 UTC, SeventhM commented on core/src/com/unciv/logic/battle/Battle.kt
> +                        "Your [${plunderingUnit.getName()}] plundered [${plunderedAmount}] [${resourceName}] from [${plunderedUnit.getName()}]",
Notification is a bit lower (line 404)

2024-12-23 06:54 UTC, yairm210 approved these changes

2024-12-25 18:38 UTC, merged