Update Simplified_Chinese.properties
yairm210/Unciv pull request #3539
Opened 2021-01-14 04:03 UTC by LuoYinChuan

Supplement the latest version of Chinese Translation

2021-01-16 19:31 UTC, yairm210 commented
Do not change file's location...

2021-01-17 05:20 UTC, shirok1 requested changes
about the translation of "Strength when attacking"

2021-01-17 05:20 UTC, shirok1 commented on 安卓/资产/jsons/翻译/Simplified_Chinese.properties
> ++[amount]% Strength when attacking = 攻击时+ [amount]％力量
这里翻译成”攻击时获得+ [amount]％战斗力加成"会不会更好，因为其他的Strength都翻译成了战斗力

2021-01-17 11:50 UTC, LuoYinChuan commented
> 不要更改文件的位置...

Sorry, this is my first time to participate in the project on GitHub, many operations are not familiar with, please forgive me

2021-01-17 12:28 UTC, LuoYinChuan commented on 安卓/资产/jsons/翻译/Simplified_Chinese.properties
> ++[amount]% Strength when attacking = 攻击时+ [amount]％力量
确实，感谢提醒

2021-01-17 12:41 UTC, closed without merging

2021-01-17 13:16 UTC, LuoYinChuan commented
谢谢您的建议，我已经翻译了你希望翻译的那个翻译Thank you for your suggestion. I have translated the one you want




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shiroki Satsuki"<notifications@github.com&gt;; 
发送时间: 2021年1月17日(星期天) 中午1:20
收件人: "yairm210/Unciv"<Unciv@noreply.github.com&gt;; 
抄送: "暮隐星灵"<2838369232@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [yairm210/Unciv] Update Simplified_Chinese.properties (#3539)






@shirok1请求对此拉请求进行更改。

“进攻时有力量”的翻译


在安卓/资产/杨森/翻译/Simplified_Chinese.properties:
&gt; @@ -3265,15 +3268,14 @@ Coastal Raider III = 海掠III级    Wolfpack I = 狼群I级   # Requires translation! -+[amount]% Strength when attacking =  - ++[amount]% Strength when attacking = 攻击时+ [amount]％力量 
这里翻译成“攻击时获得+[金额]%战斗力加成”会不会更好,因为其他的力量都翻译成了战斗力

—
因为修改了打开/关闭状态，所以您收到了此消息。
直接回复此邮件，在GitHub上查看，或取消订阅.