Update Swedish.properties
yairm210/Unciv pull request #5024
Opened 2021-08-29 13:25 UTC by Alex25820

Translated the newly added lines.

2021-08-29 20:03 UTC, SimonCeder requested changes

2021-08-29 20:03 UTC, SimonCeder commented on android/assets/jsons/translations/Swedish.properties
> +When Allies: = När Allierade:
"Som Vänner", "Som Allierade" imo. Eller kanske "Medans"

2021-08-30 05:28 UTC, Alex25820 commented on android/assets/jsons/translations/Swedish.properties
> +When Allies: = När Allierade:
Låter "Vid Vänskap:" och "Vid allians:" bättre?

2021-08-30 09:56 UTC, SimonCeder commented on android/assets/jsons/translations/Swedish.properties
> +When Allies: = När Allierade:
Låter bra!

2021-08-30 20:24 UTC, merged