Update Ukrainian.properties
yairm210/Unciv pull request #5686
Opened 2021-11-16 17:25 UTC by Marerjh

2021-11-16 19:45 UTC, xlenstra commented
Placeholder `[civName2]` not found in `Ukrainian` for entry `[civName] has married into the ruling family of [civName2], bringing them under their control.`

2021-11-22 18:43 UTC, Prosta4okua requested changes

2021-11-22 18:43 UTC, Prosta4okua commented on android/assets/jsons/translations/Ukrainian.properties
> +Not displayed as an available construction unless [building] is built = Не відображаєтьс яяк доступна споруда, поки [building] не буде споруджене
Не відображаєтьс**я**

2021-11-22 18:43 UTC, Prosta4okua commented on android/assets/jsons/translations/Ukrainian.properties
> +Requires at least one of the following resources worked near the city: = Вимагає щонайменше один з наступних ресурсів поблизу міста, клітинка котрого оброблюється:
Наступний - [калька](https://onlinecorrector.com.ua/uk/%D1%82%D0%B0%D0%BA%D0%B8%D0%B9-%D1%83-%D0%BF%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA%D1%83/).

2021-11-22 18:43 UTC, Prosta4okua commented on android/assets/jsons/translations/Ukrainian.properties
> +[civName] has married into the ruling family of [civName2], bringing them under their control. = Королі держави [civName] одружились з правлячою сім'єю держави [civName]. Тепер вони під їх контролем.
[Панівною](https://onlinecorrector.com.ua/uk/%D0%BF%D0%B0%D0%BD%D1%96%D0%B2%D0%BD%D0%B8%D0%B9-%D0%BA%D0%B5%D1%80%D1%96%D0%B2%D0%BD%D0%B8%D0%B9-%D1%83%D1%80%D1%8F%D0%B4%D1%83%D1%89%D0%B8%D0%B9/).

2021-11-22 18:43 UTC, Prosta4okua commented on android/assets/jsons/translations/Ukrainian.properties
> +[cityState] is being invaded by Barbarians! Destroy Barbarians near their territory to earn Influence. = Місто [cityState] зазнало вторгнення варварів! Знищте варварський табір поблизу їх міста щоб п
- `їх` -> `їхнього`
- Кома перед `щоб`
- І за бажанням ліпше `щоби` замість `щоб`

2021-11-22 18:43 UTC, Prosta4okua commented on android/assets/jsons/translations/Ukrainian.properties
> +'I once sent a dozen of my friends a telegram saying 'flee at once-all is discovered!' They all left town immediately.' - Mark Twain = «Якось я надіслав купці своїх друзів телеграму, у котрій писало:
Остання крапку в ялинках варто перемістити в кінець речення

2021-12-15 18:14 UTC, closed without merging