Update german.properties
yairm210/Unciv pull request #5716
Opened 2021-11-28 15:21 UTC by AngelDHaiman

Translated all the Leftover "#Requires Translation" and updated some other translations

2021-11-29 06:16 UTC, Mape6 requested changes

2021-11-29 06:16 UTC, Mape6 commented on android/assets/jsons/translations/German.properties
> +Denounce [civName]? = [civName] denunzieren?
"Denunzieren" ist zwar die direkte Übersetzung von "Denounce" aber ich fand "anprangern" besser, da es sich flüssiger liest und besser zum Geschehen in Unciv passt.

2021-11-29 06:16 UTC, Mape6 commented on android/assets/jsons/translations/German.properties
> +[civName] has made a counteroffer to your trade request = [civName] hat einen Gegenhandel zu Ihrer Handelsanfrage vorgestellt
"Gegenhandel" klingt etwas hölzern. "Gegenangebot" würde hier besser passen.
Und anstatt das förmliche "Ihr" passt hier die "Du" Variante besser.
Förmlich gibts eigenlich nur, wenn Anführer von Zivilisationen miteinander sprechen. Siehe Abschnitt zu den Zivilisationen.

2021-11-29 06:16 UTC, Mape6 commented on android/assets/jsons/translations/German.properties
> +Because they have [resource], the citizens of [cityName] are celebrating We Love The King Day! = Weil sie [resource] haben, feiern die Einwohner von [cityName] den Wir Lieben den König Tag
Satzzeichen fehlt
"Wir Lieben den König Tag" sollte eher, wie in der englischen Vorlage "Wir Lieben Den König Tag" geschrieben werden.

2021-11-29 06:16 UTC, Mape6 commented on android/assets/jsons/translations/German.properties
> +Fortify = Verschanzen
Aus diversen anderen Computerspielen kenne ich eher "Befestigen" als "Verschanzen".
Daher meine Frage: Warum wurde es von dir geändert?

2021-11-29 06:16 UTC, Mape6 commented on android/assets/jsons/translations/German.properties
> +Community = Community
Wozu die Änderung? Was ist an "Gemeinschaft" verkehrt?

2021-11-29 06:16 UTC, Mape6 commented on android/assets/jsons/translations/German.properties
> +[amount]% maintenance costs = [amount]% Instandsetungskosten
"maintenance" wird gemeinhin mit " Wartung" übersetzt. Daher bitte ändern, sodass die Übersetzungen wieder konsistent sind.

2021-11-29 06:16 UTC, Mape6 commented on android/assets/jsons/translations/German.properties
> +Your cities will periodically demand different luxury goods to satisfy their desire for new things in life. = Eure Städte werden wiederholend verschiedene Luxusgüter fordern, welche deren Verlangen n
Hier bitte wieder "Du" verwenden
"in regelmäßigen Abständen" passt aus meiner Sicht besser als "wiederholend". Was meinst du?

2021-11-29 06:16 UTC, Mape6 commented on android/assets/jsons/translations/German.properties
> +If you manage to acquire the demanded luxury by trade, expansion, or conquest, the city will celebrate We Love The King Day for 20 turns. = Wenn Sie das geforderte Luxusgut durch Handel, Grenzerweite
"Sie" bezieht sich hier auf die Bürger der Stadt, daher passt nicht die Großschreibung.
"expansion" wird gemeinhin mit "Expansion" übersetzt. Aus Einheitlichkeit daher bitte ändern.

2021-11-29 06:16 UTC, Mape6 commented on android/assets/jsons/translations/German.properties
> +During the We Love The King Day, the city will grow 25% faster. = Während des Wir lieben den König Tag, wächst ihre Stadt um 25% schneller.
"deine" anstatt "ihre"
"Während des Wir lieben den König Tag", zweiter Fall, somit kommt hinter den "Tag" noch ein "s".

2021-11-29 06:16 UTC, Mape6 commented on android/assets/jsons/translations/German.properties
> +This means exploration and trade is important to grow your cities! = Das bedeutet, dass Erkunden und Handel betreiben einen wichtigen Beitrag dazu leisten Ihre Städte wachsen zu lassen!
"Das bedeutet, dass Erkundung und Handel wichtig sind, um deine Städte wachsen zu lassen!" liest sich in meinen Augen flüssiger.

2021-12-15 18:15 UTC, yairm210 commented
Relevant?

2021-12-15 18:40 UTC, Mape6 commented
> Relevant?

Not anymore, in my opinion. I did the translations already in an other PR.

2021-12-15 19:12 UTC, closed without merging