Fixed the vanilla piety tree
yairm210/Unciv pull request #6552
Opened 2022-04-15 09:00 UTC by xlenstra

Should now contain the vanilla policies instead of the G&K policies

2022-04-15 12:29 UTC, heipizhu4 requested changes
![image](https://user-images.githubusercontent.com/100454479/163570627-9a44f0a9-4fda-4cb3-8418-2cb339af87c2.png)
I've just checked the wiki, and 'tradition complete' in vanilla only gives [+2] food in all cities, no additional growth is provided. (line65)

2022-04-16 08:35 UTC, xlenstra commented
From your screenshot:
> Adopting all policies in the Tradidition tree will grant a +15% Growth in all cities and:

Also, according to my local copy:
![image](https://user-images.githubusercontent.com/71121390/163668328-2b9f22af-3e8e-414c-af55-a40f6747266a.png)

2022-04-16 08:37 UTC, xlenstra commented
> Vanilla doesn't provide the unique in line 550

Fixed

2022-04-16 08:44 UTC, heipizhu4 approved these changes

2022-04-16 20:04 UTC, merged