Update Traditional_Chinese.properties
yairm210/Unciv pull request #6921
Opened 2022-05-23 11:18 UTC by hhpy123

2022-05-23 12:43 UTC, heipizhu4 requested changes
I suppose you should be editing in your own fork, instead of pulling a new one. You enter here: 
![image](https://user-images.githubusercontent.com/100454479/169821691-583bbfc9-a9b5-4ab7-9a49-ed85faa6e122.png)
Good enough for a beginner, but still need improvements.

2022-05-23 12:43 UTC, heipizhu4 commented on android/assets/jsons/translations/Traditional_Chinese.properties
> +Invalid input! Please enter a different string. = 輸入無效！請輸入不同的字符串。
有點翻譯腔。We don’t say “字串” in normal speaking, don’t we? Instead we can say “名字”in this sentence.

2022-05-23 12:43 UTC, heipizhu4 commented on android/assets/jsons/translations/Traditional_Chinese.properties
> +Order = 命令
Looks weird. I don't remember how civ V itself translate this word, but I suppose ‘秩序' is better.

2022-05-23 12:43 UTC, heipizhu4 commented on android/assets/jsons/translations/Traditional_Chinese.properties
> +'Thou shalt not muzzle the ox when he treadeth out the corn.' - Bible Deuteronomy 25:4 = “牛在場上踹穀的時候，不可籠住他的嘴。”——聖經·申命記　25:4
Like these 2 changes. Gonna check Simplified_Chinese translation.:D

2022-05-23 12:43 UTC, heipizhu4 commented on android/assets/jsons/translations/Traditional_Chinese.properties
> +Sword = 劍
Just for warning, you always find sword before the word 'unit'. Is 劍单位 good enough? I don't think so. How about '武装' or ’带剑'(They are not actually good enough, but it should be at least an adj.).

2022-05-23 13:23 UTC, hhpy123 commented
Thank you for some of your reminders, because I can only see the word when
translating, and I can't see where the word is used, so sometimes the
meaning is a bit strange, thank you again for your suggestion😀😀

heipizhu4 ***@***.***> 於 2022年5月23日 週一 下午8:43 寫道：

> ***@***.**** requested changes on this pull request.
>
> I suppose you should be editing in your own fork, instead of pulling a new
> one. You enter here:
> [image: image]
> <https://user-images.githubusercontent.com/100454479/169821691-583bbfc9-a9b5-4ab7-9a49-ed85faa6e122.png>
> Good enough for a beginner, but still need improvements.
> ------------------------------
>
> In android/assets/jsons/translations/Traditional_Chinese.properties
> <https://github.com/yairm210/Unciv/pull/6921#discussion_r879373538>:
>
> >   # Requires translation!
>
>  Please select a tile for this building's [improvement] =
>
>
>
>  # Ask for text or numbers popup UI
>
>
>
>   # Requires translation!
>
> -Invalid input! Please enter a different string. =
>
> +Invalid input! Please enter a different string. = 輸入無效！請輸入不同的字符串。
>
>
> 有點翻譯腔。We don’t say “字串” in normal speaking, don’t we? Instead we can say
> “名字”in this sentence.
> ------------------------------
>
> In android/assets/jsons/translations/Traditional_Chinese.properties
> <https://github.com/yairm210/Unciv/pull/6921#discussion_r879403588>:
>
> >   # Requires translation!
>
> -Order =
>
> +Order = 命令
>
>
> Looks weird. I don't remember how civ V itself translate this word, but I
> suppose ‘秩序' is better.
> ------------------------------
>
> In android/assets/jsons/translations/Traditional_Chinese.properties
> <https://github.com/yairm210/Unciv/pull/6921#discussion_r879404954>:
>
> >  Pottery = 制陶
>
> -'Thou shalt not muzzle the ox when he treadeth out the corn.' - Bible Deuteronomy 25:4 = “牛在踹穀的時候，不可籠住它的嘴。”——聖經·申命記　25:4
>
> +'Thou shalt not muzzle the ox when he treadeth out the corn.' - Bible Deuteronomy 25:4 = “牛在場上踹穀的時候，不可籠住他的嘴。”——聖經·申命記　25:4
>
>
> Like these 2 changes. Gonna check Simplified_Chinese translation.:D
> ------------------------------
>
> In android/assets/jsons/translations/Traditional_Chinese.properties
> <https://github.com/yairm210/Unciv/pull/6921#discussion_r879409955>:
>
> > @@ -4777,23 +4777,23 @@ Porcelain =
>
>  #################### Lines from UnitPromotions from Civ V - Vanilla ####################
>
>
>
>   # Requires translation!
>
> -Sword =
>
> +Sword = 劍
>
>
> Just for warning, you always find sword before the word 'unit'. Is 劍单位
> good enough? I don't think so. How about '武装' or ’带剑'(They are not actually
> good enough, but it should be at least an adj.).
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/yairm210/Unciv/pull/6921#pullrequestreview-981640571>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX57EMUIFSCKK4376QNHALLVLN4OLANCNFSM5WVPRH3A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-05-23 13:58 UTC, heipizhu4 commented
> Thank you for some of your reminders, because I can only see the word when translating, and I can't see where the word is used, so sometimes the meaning is a bit strange, thank you again for your suggestion😀😀 
You're welcome! Next time turn on the game while translating so that you can make less mistakes! Anyway, anyone can make mistakes so don't be afraid of making mistakes. I 'll be able to check these translations (most of the times) so these errors can be ticked out.😀
Looking forward to your changes!

2022-05-24 06:03 UTC, hhpy123 commented on android/assets/jsons/translations/Traditional_Chinese.properties
> +Invalid input! Please enter a different string. = 輸入無效！請輸入不同的字符串。
copy that

2022-05-24 06:06 UTC, hhpy123 commented on android/assets/jsons/translations/Traditional_Chinese.properties
> +Sword = 劍
can i ask what is this word use for?

2022-05-24 06:07 UTC, hhpy123 commented on android/assets/jsons/translations/Traditional_Chinese.properties
> +Sword = 劍
I could translate more precisely if I knew :)

2022-05-24 07:58 UTC, heipizhu4 commented on android/assets/jsons/translations/Traditional_Chinese.properties
> +Sword = 劍
```
		"name": "Warrior",
		"unitType": "Sword",
		"movement": 2,
		"strength": 8,
		"cost": 40,
		"obsoleteTech": "Metal Casting",
		"upgradesTo": "Swordsman",
		"uniques" : ["May upgrade to [Spearman] through ruins-like effects"],
		"attackSound": "nonmetalhit",
        "civilopediaText": [
			{"text": "This is your basic, club-swinging fighter."}
		]
```
You can find all the units that are `sword` [here](https://github.com/yairm210/Unciv/blob/master/android/assets/jsons/Civ%20V%20-%20Vanilla/Units.json) with a quick search of `sword`.

In game, you can find 'sword' mostly in all kinds of `uniques`, basically the functions of the units/nations/etc.
In game, you can find `uniques` in the civilopedia, but unluckily I didn't remember exactly which unique used Sword :(. Just take this screenshot as a reference.
![image](https://user-images.githubusercontent.com/100454479/169979338-2535cbaf-8d25-4293-b4da-4f42310ea573.png)
And that `mounted` can be replace with `sword` or other unit types in mods. You can find all of uniques that may contain `sword` by searching ‘Unitfilters’ in the [wiki](https://yairm210.github.io/Unciv/Modders/uniques/)

(PS: I'm still having a hard time differciate ‘Melee' and ’Sword‘ I'll come back later)

2022-05-24 08:42 UTC, hhpy123 commented on android/assets/jsons/translations/Traditional_Chinese.properties
> +Sword = 劍
If only by the literal meaning to distinguish
Melee and sword are completely different meanings
Melee means more similar to fighting in close quarters
The sword is just a metaphor for the sword, nothing else

2022-05-24 10:01 UTC, heipizhu4 requested changes
More things to correct. You can actually take Simplified_Chinese translation as a reference:D. But never copy them too often, as CHS and CHT have a slightly different language pattern.

2022-05-24 10:05 UTC, heipizhu4 commented
I have a feeling we are getting there. I hope I can't find more errors after the next commit.

2022-05-24 14:31 UTC, hhpy123 commented on android/assets/jsons/translations/Traditional_Chinese.properties
> +Siege = 大力士
I check line 6782 and i find noting, do you sure is line 6782 ?

2022-05-24 14:35 UTC, hhpy123 commented on android/assets/jsons/translations/Traditional_Chinese.properties
> +CityState = 市
tks you suggest

2022-05-24 15:23 UTC, heipizhu4 commented on android/assets/jsons/translations/Traditional_Chinese.properties
> +Siege = 大力士
Sorry, line 6826. I went to the wrong file.

2022-05-24 15:36 UTC, heipizhu4 commented on android/assets/jsons/translations/Traditional_Chinese.properties
> +Building = 建造中
```suggestion
Building = 建筑
```
I wonder why I missed this mistake. The `building` should be easy to find in game, and you can find them in the cityscreen.

2022-05-24 15:40 UTC, heipizhu4 commented
@yairm210 Would you mind bringing this PR into check? It is almost all done.
PS: Will #6920 #6921 #6924 conflict with each other?

2022-05-25 00:58 UTC, heipizhu4 approved these changes
Nice change! ❤

2022-05-26 03:29 UTC, hhpy123 commented
how do i do that

2022-05-26 03:29 UTC, hhpy123 commented
> Can you please resolve the conflicts? :)

how do i do that

2022-05-27 10:57 UTC, merged