spectators can no longer change city focus
yairm210/Unciv pull request #6946
Opened 2022-05-25 22:45 UTC by alexban011

resolves #6939

code checks if the player is a spectator and if the city is a puppet before changing the focus

2022-05-25 22:50 UTC, alexban011 commented
Actually I don't think it sets puppet city's focus to gold yet, need to do some digging

2022-05-26 05:05 UTC, itanasi commented
Better to block the onClick actions in the City Screen via the canChangeState Boolean. Similar to the other logic in CityScreen

2022-05-26 05:10 UTC, itanasi requested changes

2022-05-26 05:10 UTC, itanasi commented on core/src/com/unciv/logic/city/CityInfo.kt
> +            cityAIFocus = CityFocus.GoldFocus
Set cityAIFocus before reassignAllPopulation()

2022-05-26 05:10 UTC, itanasi commented on core/src/com/unciv/ui/cityscreen/CitizenManagementTable.kt
> +            if (!UncivGame.Current.gameInfo.currentPlayerCiv.isSpectator() && !city.isPuppet) {
Instead of checking isSpectator(), use cityScreen.canChangeState
There's also several other buttons you'll need to disable

2022-05-26 05:24 UTC, itanasi commented
I handled all the buttons if you're a Spectator in #6954.

Take a look and add in the changes needed for Puppet

2022-05-26 12:09 UTC, alexban011 commented
> Take a look and add in the changes needed for Puppet

Then I'll remove the changes for the buttons and only keep the changes for puppet, and rename the PR/make a new one to only mention the puppet changes

2022-05-26 14:12 UTC, itanasi commented
The way I'd do it is merge your branch up to master, resolve the conflicts, then adapt your code and recommit to the same branch so we have the discussion history in the same PR

2022-05-27 01:16 UTC, itanasi commented
Right now this sets the Focus between turns for the Puppetee Cities. However it leaves all of the buttons for Citizen Management active, meaning you can still use them to affect Cotizen Assignments.

Check out #6954 for all of the `OnClick()` locations that should be updated. This could be a separate PR if you'd like.

2022-05-27 03:59 UTC, itanasi commented
> > Check out #6954 for all of the OnClick() locations that should be updated
> 
> That's already merged :)

Correct, but only disabled the buttons if you're a Spectator. To complete the issue cited, we also want to disable all the buttons if the city is a Puppet

2022-05-27 06:06 UTC, alexban011 commented
> disable all the buttons if the city is a Puppet

Correct. The fix should be easy enough, I'll add it in a couple hours when I get home

2022-05-27 07:15 UTC, itanasi commented
Sorry, just made a PR #6969 that moves a bunch of those buttons around.

2022-05-27 10:52 UTC, yairm210 approved these changes

2022-05-27 10:52 UTC, merged