Refactor: Make CustomFileLocationHelper "dumb", only handling Strings, no GameInfo objects
yairm210/Unciv pull request #6962
Opened 2022-05-26 15:29 UTC by Azzurite

Also fixes the `GameInfo.customSaveLocation` to work properly for Android.

Also fixes wrong handling for canceling on Desktop, checking for `selectedFile == null` is not correct, you have to check the return code of `JFileChooser.showSaveDialog`.

Also fixes AWT code not running on the AWT dispatch thread, which at least for me, caused errors.

2022-05-26 17:26 UTC, yairm210 commented on desktop/src/com/unciv/app/desktop/CustomFileLocationHelperDesktop.kt
> +    private fun callLoadCallback(loadCompleteCallback: (SuccessfulLoadResult?, Exception?) -> Unit,
Sounds like this is cross platform logic?

2022-05-26 17:30 UTC, yairm210 commented on android/src/com/unciv/app/CustomFileLocationHelperAndroid.kt
> +            var exception: Exception? = null
This whole logic pipeline also looks cross- platform

- get platform-specific input stream
- attempt to read
- return result depending on successfulness of attempt

2022-05-26 17:31 UTC, yairm210 requested changes
Good change overall, I think the main logic can still be simplified to reduce platform-specific code

2022-05-26 19:23 UTC, SomeTroglodyte approved these changes
Load dialog _says_ "Save" in caption and OK button.
FYI: Still does `X Error of failed request:  BadWindow (invalid Window parameter)  Major opcode of failed request:  20 (X_GetProperty)` on Mint, so that one wasn't AWT threading, pity.
`SuccessfulLoadResult`: If you're wrapping for a result, why not wrap all three?
"looks cross- platform": I understand both sides: The Java.io.InputStream could be where the interface "draws the line" - but what if a platform decides Java streams aren't cutting it and comes with its own IO layer? Gdx will have a hard time, and we'd notice if that were ever the case as we use Gdx.FileHandle.file(), but still..
"callLoadCallback is cross-platform" - Looking at it, yea, hickups. But the interface "contract" says `Calls the [loadCompleteCallback] on the main thread` - and if Android can guarantee that without any postRunnable thanks to `startActivityForResult` already fulfilling that...

I'll "pre-"approve, wouldn't hurt _me_ (ok yes at least one "conflicts" extra), good approach and OP will have tested successfully on Windowz.

2022-05-27 10:51 UTC, yairm210 approved these changes
:)
Most changes are local so if they're not perfect it's simple to make the future changes
But code that needs knowledge of 3 files. in this case, is much harder to refactor once it's settled in

2022-05-27 10:59 UTC, yairm210 commented
Check that I made the correct conflict resolution :)

2022-05-27 13:28 UTC, SomeTroglodyte commented
> Check that I made the correct conflict resolution :)

From the condensed view yes, but I fear that wouldn't cover simple accidental deletions. So - a short skim of the entire PR diff says yes no spurious bits or losses I can see. But Timo would know their code better.

2022-05-27 13:53 UTC, merged