Translation for 4.2.3
yairm210/Unciv pull request #7695
Opened 2022-08-23 06:22 UTC by heipizhu4

2022-08-23 08:07 UTC, Qiayeb commented
thanks for you invite, i will edit in your fork

2022-08-23 08:19 UTC, xk730 commented
抱歉，但不得不说，我和其他中文开发人员目前无法认同您的大部分修改。
例如您将”我们爱戴领袖日“修改为了”我爱领袖节“，我不知道您是出于什么缘故将 We 翻译成为了”我“

2022-08-23 08:20 UTC, xk730 commented
Sorry, but I have to say that I and other Chinese developers cannot agree with most of your changes at present.
For example, you changed "we love leaders day" to "I love leaders day". I don't know why you translated "we" into "I"“

2022-08-23 08:24 UTC, heipizhu4 commented
> 抱歉，但不得不说，我和其他中文开发人员目前无法认同您的大部分修改。 例如您将”我们爱戴领袖日“修改为了”我爱领袖节“，我不知道您是出于什么缘故将 We 翻译成为了”我“

个人认为，使用“我们爱领袖日”或“我们爱戴国王日”均可。没记错的话，一个是原始繁中，另一个是原始简中的翻译

2022-08-23 08:27 UTC, Qiayeb commented
> 抱歉，但你说修改，我和其他中文的时候，你的角色会被 修改我们翻译成了“我”

This part uses free translation, the original translation is difficult to understand in simplified Chinese, and this festival can be regarded as the celebration of all citizens, and this celebration can also be a spontaneous activity of each citizen

2022-08-23 08:29 UTC, xlenstra commented
Though this currently doesn't conflict with #7698 and so both can me merged, I'll let you discuss the changes made in this PR before marking it as a mergeable translation

2022-08-23 08:34 UTC, heipizhu4 commented
> Though this currently doesn't conflict with #7698 and so both can me merged, I'll let you discuss the changes made in this PR before marking it as a mergeable translation

Well, I made the resolve in b7785ce5513c19157f65e27c237ed6ad40a470fa

2022-08-23 08:39 UTC, xlenstra commented
I agree, there are no conflicts, but xk730 seems to disagree with some of the changes you and Qiayeb have made. I'll give you some time to discuss these changes before this is marked as a mergeable translation

2022-08-23 08:47 UTC, Qiayeb commented
> 

i agree his opinion , but just to find the replacement WLTK, because i also changed its grammar. But “目前无法认同您的大部分修改” for why? Is there a few trans is wrong？要知道中文翻译者不完全代表简体中文, fork needs to be fed back correctly

2022-08-23 08:51 UTC, heipizhu4 commented
> > 
> 
> i agree his opinion , but just to find the replacement WLTK, because i also changed its grammar. But “目前无法认同您的大部分修改” for why? Is there a few trans is wrong？要知道中文翻译者不完全代表简体中文, fork needs to be fed back correctly

不说WLTK的事，大多数都不错。那些100%错误的东西都已经在合并更改的时候解决了。详见#7698中的review.

2022-08-23 08:57 UTC, Qiayeb commented
> 

就在修改后合并吧，新的翻译已经在路上了，未来的更新会持续援引Civ6或图文说明

2022-08-23 09:14 UTC, heipizhu4 commented
👍

2022-08-23 09:37 UTC, xk730 commented
您不能这么说，因为我从来没说谁代表着什么。我只是认为这些问题值得讨论

2022-08-23 09:37 UTC, xk730 commented
如果您还坚持认为自己大多数不存在问题，那么我们可以再举例子

2022-08-23 09:39 UTC, xk730 commented
比如说 腾格里苍天 的修改我个人并不认为有这个必要。
按照英文对照法则，您大可不必修改，况且在civ5中也没有突出“苍天”这个元素

2022-08-23 09:41 UTC, xk730 commented
我也不认为 您将 we 翻译成 “我”有助于玩家们理解

2022-08-23 09:43 UTC, xk730 commented
“协议到期"和协议结束在您的眼中有什么区别吗？还是说您只是想根据您的日常用语修改他们？？

2022-08-23 09:46 UTC, xk730 commented on android/assets/jsons/translations/Simplified_Chinese.properties
> +Invalid input! Please enter a different string. = 无效的输入！请换个名字试试。
还有形如这种翻译修改，有什么具体意义吗？您是觉得原本的翻译是文言文晦涩难懂吗？？？

2022-08-23 09:46 UTC, xk730 commented on android/assets/jsons/translations/Simplified_Chinese.properties
> -[turnsToStarvation] turns to lose population = 此城市将在[turnsToStarvation]轮后失去 1 个市民
您为什么将 城市删除了？您是觉得将 城市 删除更容易理解吗？

2022-08-23 09:49 UTC, xk730 commented on android/assets/jsons/translations/Simplified_Chinese.properties
> +Closest city = 最近行政区
您为什么要将这里的 “city”翻译成 “行政区”？？

2022-08-23 09:49 UTC, xk730 commented on android/assets/jsons/translations/Simplified_Chinese.properties
> +WLTK- = 需求量
“需求数量”和“需求量”有什么区别吗？您在修改什么？

2022-08-23 09:49 UTC, xk730 commented
此外对于政策名称的修改我也并不认同

2022-08-23 09:51 UTC, xk730 commented
我再强调一下我的朋友，您提交的翻译中有很多值得称赞的地方，这是无疑的。我和与我联系的开发者、mod作者以及玩家只是希望能够提出我们的疑问，仅此而已。：）

2022-08-23 10:21 UTC, xk730 commented
> > 我再强调一下我的朋友，您提交的翻译中有很多值得称赞的地方，这是无疑的。我和与我联系的开发者、mod作者以及玩家只是希望能够提出我们的疑问，仅此而已。看到多达260处的修改，我想您一定准备了很久，我个人只是希望他能够更加适合一些。：）
> 
> #### 信、达、雅
> #### Keep the player interested in playing, achieve translation goals, and use concise and beautiful vocabulary
> > 这是翻译的基本要求
> > If a machine can translate and reach the same conclusions as you, why is the work of translation public content?
> 
> 当您只是在发出疑问而非质疑的时候，我觉得这就有必要去思考为什么。我在我所有的必要修正内都做了解释，它在我的分支内容评论下。
> 
> 我的修改内容基于玩家的游玩体验上，他们经常抱怨机器翻译的内容太多，然而在我查证之后，这些基本上都是由人工翻译的。 I can tell you that most of your complained translations are based on feedback I received from players who may have played different games, like Civ 6 and Iron 4.
> 
> If you have any more questions, please find a Chinese player and inject this properties into the game and let's hear what he thinks. 所以说您可以表达对内容阐述的质疑。但是，在部分场合这些翻译内容占据了绝大空间，反而不适合查阅和影响理解。
> 
> This reply takes into account the need for repeated translation, ah, of course, in the actual translation of the document does not need to reach this level, because it will sounds too strange. 由此可见，我是先发现了不能接受的地方，然后再在文件中寻找这项翻译并修改。 This is the way players complain to me that it's hard for them to come to this place and give feedback, but I collect some of it. 希望您在抱怨之余能够尊重我的工作量，并在实际内容上进行反馈和修改。 To My colleagues

很高兴能够看到您的详细解释；我不清楚是哪些玩家向您反馈当前的中文内容晦涩难懂（例如“需求数量”难以理解但“需求量”可以理解？），但实际上就我而言我很多您修改的地方我 从来没有 看到过玩家抱怨说“看不懂”

2022-08-23 10:26 UTC, xk730 commented
因为每个人都可能出现“口语化翻译”，所以我将会请unciv的一些中文玩家讨论这个问题——以保证真正符合玩家的看法

2022-08-23 10:30 UTC, Qiayeb commented
> 因为每个人都可能出现“口语化翻译”，所以我将会请unciv的一些中文玩家讨论这个问题——以保证真正符合玩家的看法

That's why I'm saying that the next time I translate, it's more powerful to combine screenshots of the before and after (and maybe you need to post screenshots of the player's opinions?). It's a waste of time.) you also know that the time I write this word will make me translate more content, and adding pictures is making it more difficult to participate.
I hope your time can also be used in these aspects: play games and feedback questions, translate and correct content in a real place, why translate in this way, borrow the machine directly to retain the original intention, you can show the puzzling button, so that everyone can see at a glance.

2022-08-23 10:34 UTC, xk730 commented
> 

我并不需要发布什么“截图”玩家亲自发声将是最好的依据；而且我希望您能够理解：讨论是开发的一部分，而不是闭门造车

2022-08-23 10:34 UTC, xk730 commented
> > 因为每个人都可能出现“口语化翻译”，所以我将会请unciv的一些中文玩家讨论这个问题——以保证真正符合玩家的看法
> 
> That's why I'm saying that the next time I translate, it's more powerful to combine screenshots of the before and after (and maybe you need to post screenshots of the player's opinions?). It's a waste of time.) you also know that the time I write this word will make me translate more content, and adding pictures is making it more difficult to participate. I hope your time can also be used in these aspects: play games and feedback questions, translate and correct content in a real place, why translate in this way, borrow the machine directly to retain the original intention, you can show the puzzling button, so that everyone can see at a glance.

我并不需要发布什么“截图”玩家亲自发声将是最好的依据；而且我希望您能够理解：讨论是开发的一部分，而不是闭门造车

2022-08-23 10:46 UTC, Qiayeb commented
Another user, the role model front on you deserve to learn. what can said ''If you do now, you will improve.If you don't have anything to modify, compliment him.''Don't let every player assume that the game is not alive in Chinese translators to translate.
是谁追着不放？是谁在全盘否定还在那边婉言宽慰？您的贡献也来让我评评？你成功地惹怒了一个人，用骚扰的方式！您是否注意到我竭力在为开发者展示讨论的过程？向我展示你的翻译官证件，然后你就可以在这个项目上工作——哦天哪，当我用英文写出这段试探性的语句我已经笑出了声！看看，独属于你的工作！不包含任何的我！

2022-08-23 11:20 UTC, xk730 commented
> Another user, the role model front on you deserve to learn. what can said ''If you do now, you will improve.If you don't have anything to modify, compliment him.''Don't let every player assume that the game is not alive in Chinese translators to translate. 是谁追着不放？是谁在全盘否定还在那边婉言宽慰？您的贡献也来让我评评？你成功地惹怒了一个人，用骚扰的方式！您是否注意到我竭力在为开发者展示讨论的过程？向我展示你的翻译官证件，然后你就可以在这个项目上工作——哦天哪，当我用英文写出这段试探性的语句我已经笑出了声！看看，独属于你的工作！不包含任何的我！

很抱歉，但是我无法理解当我提出不同意见时您为何定义我为“追着不放”，而且从来没有人要求您不得进行中文翻译工作！！
最重要的是请不要进行主观怀疑！！您如果认为我的观点有问题，我完全同意您对我进行反驳，但不是对我进行个人攻击！：（

2022-08-23 12:04 UTC, Qiayeb commented
已经通过的国内程序道德许可、已经通过的国内开发者的道德许可、已征得三位以上玩家的同意和回复内容审查：
这句话我已准备许久，直到有人阻拦我的树枝，俚看上去完全不像是madarin母语者，这是对所有参与者的声明：
投放之前我先会转播此回复 @xk730 ，众人的决断我的态度，后续仍有回复视作骚扰内容。您在群聊内的赞美之词我已经有所耳闻，我有权保持沉默，鉴于您已经做出了无法挽回的举动。如果您无法完成正确的汉化工作事项，以下是我在您第一次回复时就已准备好的结尾符。我会亲手扼杀我在这三天糟糕的github之旅，翻译竟然让我感到不快乐。
任何人都可以顶替我完成这项工作，除了你【xk730】，你的咸味倡议让我感到齁腻。

既然您已经提到了“开发”，很好，我觉得讨论已经没有必要了，您直接在纷争的分支里提交您认为最恰当的版本，我会单独的为国内的玩家准备一个简练的汉化包mod（事实上在我之前早已经有人准备过了一次，而且大部分内容也没有被采纳，我也不知道为什么。）很可惜，这里并不是国内最方便最简单的渠道，也许我并不适合担任译者，将它及时地带回去才是我要做的——为玩家服务而不是开发者和协作者。
我希望也永远不希望你能看到我的小众翻译，xk730，我的乐趣并不在于此，你已经毁灭干净了。
“人身攻击是什么？”是你背地里抓牛角尖的样子，你的时间甚至都不愿拿来做翻译！
Developer, I feel so sorry that to compare it with you in a group, if I still have seldom rights, I quit
The bad environment does not allow me to continue to provide the official what, I completely leave the game and project

2022-08-23 14:15 UTC, heipizhu4 commented on android/assets/jsons/translations/Simplified_Chinese.properties
> +Closest city = 最近行政区
```suggestion
Closest city = 最近的城市
```
Agree with xk730

2022-08-23 14:18 UTC, heipizhu4 commented on android/assets/jsons/translations/Simplified_Chinese.properties
> +WLTK- = 需求量
小修勿喷，改了就改了，也没必要可以编辑战

2022-08-23 14:19 UTC, heipizhu4 commented on android/assets/jsons/translations/Simplified_Chinese.properties
> +Invalid input! Please enter a different string. = 无效的输入！请换个名字试试。
问题不大。保留即可。

2022-08-23 14:20 UTC, heipizhu4 commented on android/assets/jsons/translations/Simplified_Chinese.properties
> +Tengriism = 腾格里苍天
确有待商榷，先暂时保留原稿。不过苍天也有一定的道理。
```suggestion
Tengriism = 腾格里信仰
```

2022-08-23 15:13 UTC, heipizhu4 commented
> 已经通过的国内程序道德许可、已经通过的国内开发者的道德许可、已征得三位以上玩家的同意和回复内容审查： 这句话我已准备许久，直到有人阻拦我的树枝，俚看上去完全不像是madarin母语者，这是对所有参与者的声明： 投放之前我先会转播此回复 @xk730 ，众人的决断我的态度，后续仍有回复视作骚扰内容。您在群聊内的赞美之词我已经有所耳闻，我有权保持沉默，鉴于您已经做出了无法挽回的举动。如果您无法完成正确的汉化工作事项，以下是我在您第一次回复时就已准备好的结尾符。我会亲手扼杀我在这三天糟糕的github之旅，翻译竟然让我感到不快乐。 任何人都可以顶替我完成这项工作，除了你【xk730】，你的咸味倡议让我感到齁腻。
> 
> 既然您已经提到了“开发”，很好，我觉得讨论已经没有必要了，您直接在纷争的分支里提交您认为最恰当的版本，我会单独的为国内的玩家准备一个简练的汉化包mod（事实上在我之前早已经有人准备过了一次，而且大部分内容也没有被采纳，我也不知道为什么。）很可惜，这里并不是国内最方便最简单的渠道，也许我并不适合担任译者，将它及时地带回去才是我要做的——为玩家服务而不是开发者和协作者。 我希望也永远不希望你能看到我的小众翻译，xk730，我的乐趣并不在于此，你已经毁灭干净了。 “人身攻击是什么？”是你背地里抓牛角尖的样子，你的时间甚至都不愿拿来做翻译！ Developer, I feel so sorry that to compare it with you in a group, if I still have seldom rights, I quit The bad environment does not allow me to continue to provide the official what, I completely leave the game and project

@Qiayeb @xk730 I'm writing this reply in Chinese. Just for 3 of us.
作为一个unciv至少25PR的翻译，我可以作证xk730确有翻译，不信去翻以前的PR记录。我会尽可能用中立的话来写这条回复。
首先，对xk730说的话。您说的一部分comment确实有失一定水准。有一部分不用刻意被纠的点被提出来，而且被人怀疑钻牛角尖确实情有可原。
其次，对于这位来讲，在查看您的翻译后确实一部分是有错误的（已在您的PR中指出）。同时，我也想要冒昧地指出，您的翻译中有一部分内容（如将city的翻译改为行政区）的内容确实非常激进，如果需要改的话可能需要全篇更改。此外，unciv是一个文明5的开源remake。我不认为对一些关键性语句（如city等）是一个好想法，因为我们依然要考虑到我们的玩家群体中包含不少真正意义上的老玩家，这种更改会对他们产生困扰。不过，您依然有对部分细节进行您认为更好的翻译。
以上。希望unciv社区越来越好。我会对这条PR进行善后，对一些具有争议性的问题暂时保持与原版文明5的简中或繁中翻译保持相同。

2022-08-23 15:28 UTC, xk730 commented
> 已经通过的国内程序道德许可、已经通过的国内开发者的道德许可、已征得三位以上玩家的同意和回复内容审查： 这句话我已准备许久，直到有人阻拦我的树枝，俚看上去完全不像是madarin母语者，这是对所有参与者的声明： 投放之前我先会转播此回复 @xk730 ，众人的决断我的态度，后续仍有回复视作骚扰内容。您在群聊内的赞美之词我已经有所耳闻，我有权保持沉默，鉴于您已经做出了无法挽回的举动。如果您无法完成正确的汉化工作事项，以下是我在您第一次回复时就已准备好的结尾符。我会亲手扼杀我在这三天糟糕的github之旅，翻译竟然让我感到不快乐。 任何人都可以顶替我完成这项工作，除了你【xk730】，你的咸味倡议让我感到齁腻。
> 
> 既然您已经提到了“开发”，很好，我觉得讨论已经没有必要了，您直接在纷争的分支里提交您认为最恰当的版本，我会单独的为国内的玩家准备一个简练的汉化包mod（事实上在我之前早已经有人准备过了一次，而且大部分内容也没有被采纳，我也不知道为什么。）很可惜，这里并不是国内最方便最简单的渠道，也许我并不适合担任译者，将它及时地带回去才是我要做的——为玩家服务而不是开发者和协作者。 我希望也永远不希望你能看到我的小众翻译，xk730，我的乐趣并不在于此，你已经毁灭干净了。 “人身攻击是什么？”是你背地里抓牛角尖的样子，你的时间甚至都不愿拿来做翻译！ Developer, I feel so sorry that to compare it with you in a group, if I still have seldom rights, I quit The bad environment does not allow me to continue to provide the official what, I completely leave the game and project

虽然您的话似乎并不流畅，但我大致理解了您的意思。您对我的第二次人身攻击令我十分难过，但既然你再次书写了这么长的“控告”内容，那么我也不得不回应您：
1.您说“我在群聊中'赞美您’“，我不知道您从哪个地方听到的；事实上是：当一开始我提出不同观点时，您说我并不能代表什么；我想这是正确的——玩家的观点才真正具有代表意义，所以我在群中咨询了玩家们的意见。我不知道您经历了什么导致您将我向玩家征集建议的过程定义为背地里辱骂您——我仍然强调：**我的观点是具有分歧的翻译，而不是某个人**
2.我从始至终没有任何阻止您担任翻译这一角色——我也明确表达过您的这个分支显然有不少可以采纳的好地方，我不知道您有没有看到这句话。
3.您说我不拿出时间做翻译工作，认为我的工作态度有问题；很抱歉，当我听到后我不是很开心。我从2019年年底加入unciv社区后一直在尝试融入大家——我的英语并不是那么好。从一开始在中文群聊和朋友们进行多人游戏，到加入discord社区，再到一点一点摸索github的功能，我不认为这其中哪一步是特别轻松的——甚至有很多中国玩家没法完成注册discord账号。我不断适应不同文化与风格——这其中我也犯过很多错误。自从我适应了工作之后，我在不断挑战自我的同时，坚持着原本的工作——除了形如即将高考无法使用电子设备等时间里，我一直坚持面向中国大陆玩家发布中文日志，不断收集反馈玩家建议，不断为不方便下载unciv游戏的玩家提供位于中国的下载服务以及搭建中文社区——这一切过程中消耗的资金完全是我和我的家庭在承担。
我可以很明确的告诉您，在今年很长的一段时间里，我和heipizhu先生一直保持友好的沟通，我们交替轮换进行中文翻译工作，并且相互交换意见。而在中文社区，但凡是我力所能及的范围内，我都会很大程度支持正在参与unciv内容制作（包括绘图、mod）的人以及帮助想要参与的人。因为我的初衷很简单：1，提升自我，增长本领。2，为开发者以及玩家搭建适合他们的平台。3，支持unciv开发工作。
而且话说回来，我在八月初完成了一段时间的工作后就离开了我的电脑——在外旅游了一段时间，而在我旅游出发之前，heipizhu先生也外出旅游了一段时间，我想这种事情都是情理之中的——谁不想看看诗与远方？如果您认为我的工作存在不足，请您提出合理的建议而不是进行人身攻击，如果您是因此就否定了我的工作，那我真的感觉很冤枉。

2022-08-23 15:36 UTC, xk730 approved these changes

2022-08-23 15:56 UTC, heipizhu4 reviewed
Haven't touched the policy part, gonna check the game tomorrow.

2022-08-23 15:56 UTC, heipizhu4 commented on android/assets/jsons/translations/Simplified_Chinese.properties
> +[turnsToExpansion] turns to expansion = 此地 [turnsToExpansion] 轮之后会扩张行政区
```suggestion
[turnsToExpansion] turns to expansion = 此地 [turnsToExpansion] 轮之后会扩张
```
Rollback

2022-08-23 15:56 UTC, heipizhu4 commented on android/assets/jsons/translations/Simplified_Chinese.properties
> +[turnsToPopulation] turns to new population = 此地 [turnsToPopulation] 轮之后增加 1 人口
```suggestion
[turnsToPopulation] turns to new population = 该城市[turnsToPopulation] 轮之后增加 1 人口
```
合并

2022-08-23 15:56 UTC, heipizhu4 commented on android/assets/jsons/translations/Simplified_Chinese.properties
> +[turnsToStarvation] turns to lose population = 此地 [turnsToStarvation] 轮之后削减 1 人口
```suggestion
[turnsToStarvation] turns to lose population = 该城市 [turnsToStarvation] 轮之后削减 1 人口
```

2022-08-23 15:56 UTC, heipizhu4 commented on android/assets/jsons/translations/Simplified_Chinese.properties
> +[relativeAmount]% [stat] from every follower, up to [relativeAmount2]% = 每个信徒都[relativeAmount]% [stat] [+1]% [Production] ，但是最多到 [relativeAmount2]%
```suggestion
[relativeAmount]% [stat] from every follower, up to [relativeAmount2]% = 每个信徒都[relativeAmount]% [stat] ，但是最多到 [relativeAmount2]%
```
防crash

2022-08-24 06:06 UTC, heipizhu4 reviewed
Just rollback the policy translation

2022-08-24 06:06 UTC, heipizhu4 commented on android/assets/jsons/translations/Simplified_Chinese.properties
> +Commerce = 商贸政策
```suggestion
Commerce = 商业政策
```
同上

2022-08-24 06:07 UTC, heipizhu4 commented on android/assets/jsons/translations/Simplified_Chinese.properties
> -[turnsToStarvation] turns to lose population = 此城市将在[turnsToStarvation]轮后失去 1 个市民
已改回

2022-08-25 01:00 UTC, Qiayeb commented
我只是上来进行销号。
很荣幸能够再次看到你的长篇大论。
这是最后一次跟你在这里回复了，以一个稍微大一点的人的角度。所以就用各位的母语来讲了，因为也没必要给别人看。

不仅是我，我的朋友们也觉得您的话语比较的“上火”、很“冲”。不仅在中文句式中，就算在英语句式中经常性的疑问反问和设问，都是招人讨厌的。

在这个工作流当中，我始终恪守着自己的原则，直到我爆发开始破口大骂。heipizhu的态度很友好，我想如果是他提出的建议，我会当时毫不犹豫的马上主动去选择修改。诚然，我不应该对你们之间任何额外的信息进行推测，但是我大概也能知道你们俩应该在现实之中也是较为密切的朋友。

> “从2019年年底加入unciv社区后一直在尝试融入大家——我的英语并不是那么好。从一开始在中文群聊和朋友们进行多人游戏，到加入discord社区，再到一点一点摸索github的功能，我不认为这其中哪一步是特别轻松的——甚至有很多中国玩家没法完成注册discord账号。”

↑哦看看，把这个年份改一下，再换成是我。然后在你摸索的时候，也有一个像你一样的人在那边重复着这些话语，你会感觉如何？我在一开始甚至是我上交的第一次的时候，我便已经有过描述，我说我是第一次，甚至我在提交第一次申请的时候都没有正确的提交，而第二次heipizhu也在提醒我标题不对，他的言语很和蔼，让我也忍不住的想加入到他的分支中。

> 我不知道您从哪个地方听到的；事实上是：当一开始我提出不同观点时，您说我并不能代表什么；我想这是正确的——玩家的观点才真正具有代表意义，所以我在群中咨询了玩家们的意见。我不知道您经历了什么导致您将我向玩家征集。

↑
事实上我全程观看了你对我的批判，我的那点微不足道的贡献，在你嘴中价值两个消息，而仅仅是某个引火线的节日你都能说成有几十条翻译内容，但凡有过认真的翻译，而且就算在你旅游之前，我想这段内容就已经存在了。我在这个游戏的时间并不比你晚，可是您对这款游戏的了解程度甚至都不如我，或者说是对这份游戏内的翻译工作。并且这几个矛盾点，你反复的在群内强调，还称我在音译、擅自主张、阴阳怪气的能力上十分出众。

我忍住了，没有出来，当时的我的想法是，我贡献了一百五十条，如果你持续的拿这件事开刀超过一百五十条，我便觉得你已经全部否定了我的翻译工作，我可以离开了，我便会终止这项对我来说毫无收获的旅途。

我对您翻译工作耗时之类的并不是我主观所想表达的。我只是想说你我之间的争论的精力太过浪费，你完全可以用于直接回退。我们之间争吵的时间至少耗费了我三个小时，这段时间您完全可以拿来复习，您需要高考的内容，而我也可以安安心心的去干一些别的事，然而就为了这些没有用的事情，我们争论了将近三个小时！在外面！

我不知道有些词您到底有没有看懂，但是有些人之常情的事情就是——面子、面子以及面子。

在这里重申一遍，我并没有对你进行任何的人身攻击，而你在反馈问题的时候，一味的在夸大其程度。用词极为不妥当，我认为你并没有进行一个中立性的评判，并且我在您的第一次评论便收获了人身攻击。

我很冷静，我不仅写了如上这么多内容，我也私下里整理和思考了许多，删除了约三万多字的疯狂内容，仅仅因为我退出了与你的这段糟糕的对话。我并没有将我的全部想法交付给你，因为我知道这会让你生气。

我否定的不是你的工作，而是你为人处事的态度。特别是在这种协作的环境中，用语和蔼以及行为能力是重要的，而且在你描述您是高三学生的时候，我甚至都不敢相信您的英语水平居然……事先我将您跟其他翻译者一样一致，同仁视为可以及时阅读并理解和翻译英语的优质翻译者，因为你提到你和大多数翻译者无法认可我的大多数翻译内容。

然而在接下来与您的对话中，我发现您的用词不仅极不严谨，而且似乎对我的英文内容都理解有了出入？我甚至特地打开了翻译器进行翻译，并没有发现多少谬论。

下面是某个扔在垃圾堆里的3万字长篇大论的节选：
*这次评论的两个协作者，他们的态度可以说是天差地别，有的态度很诚恳，建议很宽容，有的抓着不放，拿出去到处挥舞*

至于您想要扩大化github使用量的言行，鉴于您之前表达程度以及内容，我思考再三，暂且归为您是想让更多的unciv玩家学会进入github之中。可以这么理解吗？

我认为人与人之间必须要有深度的了解，而不是看到只言片语就直接下定论。

另外，不要拿家境并不殷实作为借口。真正居于陋室的人，并不会像您一样如此的吹毛求疵，别告诉我语文老师没教过你。

希望您在这我在这个网站销号后的时间里进行评论的时候，能够输入完了再删除，别什么东西都一股脑的往上面发，就算您不认识到这个问题，但是身边的人应该也认识到了这个问题，就是您的话语比较地**伤人**。

> 您提交的翻译中有很多值得称赞的地方

↑您是否只会对我说这一种好话？不好意思，这大概看起来像个客套话，我并没有得到你真心的赞誉。

> 因为我的初衷很简单：1，提升自我，增长本领。2，为开发者以及玩家搭建适合他们的平台。3，支持unciv开发工作。

↑很好的初衷，如果你有注意到我这样举例，只是用来回应你一遍遍的重复检举我的一些错误，那么你应该也是时候提升一下自我了，先从言行开始吧。哦，我说的应该说一声，您近期的一次更新的内容在实际使用中看起来很奇怪哦，我并不需要提醒你，因为我已经离开了，翻译并不是由我负责。

↑幽默和恶心人是两种东西，前提是你用词准确妥当，因为你是个翻译。

以下内容是单独留给heipizhu的，因为您的言行举止，我留给你的其实并不多：

对于牵一发动全身的翻译我从一开始就做过，因为每次的修改都是基于我重新进入游戏进行的直接感受，我也很清楚游戏中大部分语句是由早期的版本进行的翻译。
由于最近几次几乎没有翻译，我才在这些天着手研究如何翻译和理解游戏逻辑框架并且找到了github的这个数据库并注册了账号来上传我的更改内容，其中不乏有错误笔画问题以及翻译内容问题，甚至于在一些你看不到的早期版本里，我还格式化错误了。（此处呼应某人的卖惨行为

翻译是个兼职，尽管那条翻译在您看来是有些激进，但是在他人的实际游玩体验中确实并不起眼。

> 作为一个unciv至少25PR的翻译，我可以作证xk730确有翻译，不信去翻以前的PR记录。我会尽可能用中立的话来写这条回复。

我并不是在质疑他的贡献，而是在嘲笑他说话时像个锱铢必较的奸商。当然我对我那次失态负责，因为我真的忍不住了，所以用了一些委婉的词语来表达，不过我并不会为此去修改那个时间点的我的情绪，因为那也是我唯一一次最生气的时候。我不会骂人，除非我真的忍不住。

是的，我们得尊重每一个人，但是一个人就能影响到整个环境，水至清则无鱼，当我认为一个地方给我带来的快乐和成就感已经远低于时间成本以及获取到的自尊心的时候，我会选择主动离开。

我得走了，我再度在这里留下文字，只是为了说教，并不是什么激烈的行为，给每一个人一次机会，我并不会说出来，直到我怒了。

2022-08-25 03:25 UTC, xk730 approved these changes

2022-08-25 03:26 UTC, xk730 requested changes

2022-08-25 03:26 UTC, xk730 commented on android/assets/jsons/translations/Simplified_Chinese.properties
>  # Documentation: https://f-droid.org/en/docs/Build_Metadata_Reference/#Summary
1111

2022-08-25 04:05 UTC, xk730 commented
> 我只是上来进行销号。 很荣幸能够再次看到你的长篇大论。 这是最后一次跟你在这里回复了，以一个稍微大一点的人的角度。所以就用各位的母语来讲了，因为也没必要给别人看。
> 
> 不仅是我，我的朋友们也觉得您的话语比较的“上火”、很“冲”。不仅在中文句式中，就算在英语句式中经常性的疑问反问和设问，都是招人讨厌的。
> 
> 在这个工作流当中，我始终恪守着自己的原则，直到我爆发开始破口大骂。heipizhu的态度很友好，我想如果是他提出的建议，我会当时毫不犹豫的马上主动去选择修改。诚然，我不应该对你们之间任何额外的信息进行推测，但是我大概也能知道你们俩应该在现实之中也是较为密切的朋友。
> 
> > “从2019年年底加入unciv社区后一直在尝试融入大家——我的英语并不是那么好。从一开始在中文群聊和朋友们进行多人游戏，到加入discord社区，再到一点一点摸索github的功能，我不认为这其中哪一步是特别轻松的——甚至有很多中国玩家没法完成注册discord账号。”
> 
> ↑哦看看，把这个年份改一下，再换成是我。然后在你摸索的时候，也有一个像你一样的人在那边重复着这些话语，你会感觉如何？我在一开始甚至是我上交的第一次的时候，我便已经有过描述，我说我是第一次，甚至我在提交第一次申请的时候都没有正确的提交，而第二次heipizhu也在提醒我标题不对，他的言语很和蔼，让我也忍不住的想加入到他的分支中。
> 
> > 我不知道您从哪个地方听到的；事实上是：当一开始我提出不同观点时，您说我并不能代表什么；我想这是正确的——玩家的观点才真正具有代表意义，所以我在群中咨询了玩家们的意见。我不知道您经历了什么导致您将我向玩家征集。
> 
> ↑ 事实上我全程观看了你对我的批判，我的那点微不足道的贡献，在你嘴中价值两个消息，而仅仅是某个引火线的节日你都能说成有几十条翻译内容，但凡有过认真的翻译，而且就算在你旅游之前，我想这段内容就已经存在了。我在这个游戏的时间并不比你晚，可是您对这款游戏的了解程度甚至都不如我，或者说是对这份游戏内的翻译工作。并且这几个矛盾点，你反复的在群内强调，还称我在音译、擅自主张、阴阳怪气的能力上十分出众。
> 
> 我忍住了，没有出来，当时的我的想法是，我贡献了一百五十条，如果你持续的拿这件事开刀超过一百五十条，我便觉得你已经全部否定了我的翻译工作，我可以离开了，我便会终止这项对我来说毫无收获的旅途。
> 
> 我对您翻译工作耗时之类的并不是我主观所想表达的。我只是想说你我之间的争论的精力太过浪费，你完全可以用于直接回退。我们之间争吵的时间至少耗费了我三个小时，这段时间您完全可以拿来复习，您需要高考的内容，而我也可以安安心心的去干一些别的事，然而就为了这些没有用的事情，我们争论了将近三个小时！在外面！
> 
> 我不知道有些词您到底有没有看懂，但是有些人之常情的事情就是——面子、面子以及面子。
> 
> 在这里重申一遍，我并没有对你进行任何的人身攻击，而你在反馈问题的时候，一味的在夸大其程度。用词极为不妥当，我认为你并没有进行一个中立性的评判，并且我在您的第一次评论便收获了人身攻击。
> 
> 我很冷静，我不仅写了如上这么多内容，我也私下里整理和思考了许多，删除了约三万多字的疯狂内容，仅仅因为我退出了与你的这段糟糕的对话。我并没有将我的全部想法交付给你，因为我知道这会让你生气。
> 
> 我否定的不是你的工作，而是你为人处事的态度。特别是在这种协作的环境中，用语和蔼以及行为能力是重要的，而且在你描述您是高三学生的时候，我甚至都不敢相信您的英语水平居然……事先我将您跟其他翻译者一样一致，同仁视为可以及时阅读并理解和翻译英语的优质翻译者，因为你提到你和大多数翻译者无法认可我的大多数翻译内容。
> 
> 然而在接下来与您的对话中，我发现您的用词不仅极不严谨，而且似乎对我的英文内容都理解有了出入？我甚至特地打开了翻译器进行翻译，并没有发现多少谬论。
> 
> 下面是某个扔在垃圾堆里的3万字长篇大论的节选： _这次评论的两个协作者，他们的态度可以说是天差地别，有的态度很诚恳，建议很宽容，有的抓着不放，拿出去到处挥舞_
> 
> 至于您想要扩大化github使用量的言行，鉴于您之前表达程度以及内容，我思考再三，暂且归为您是想让更多的unciv玩家学会进入github之中。可以这么理解吗？
> 
> 我认为人与人之间必须要有深度的了解，而不是看到只言片语就直接下定论。
> 
> 另外，不要拿家境并不殷实作为借口。真正居于陋室的人，并不会像您一样如此的吹毛求疵，别告诉我语文老师没教过你。
> 
> 希望您在这我在这个网站销号后的时间里进行评论的时候，能够输入完了再删除，别什么东西都一股脑的往上面发，就算您不认识到这个问题，但是身边的人应该也认识到了这个问题，就是您的话语比较地**伤人**。
> 
> > 您提交的翻译中有很多值得称赞的地方
> 
> ↑您是否只会对我说这一种好话？不好意思，这大概看起来像个客套话，我并没有得到你真心的赞誉。
> 
> > 因为我的初衷很简单：1，提升自我，增长本领。2，为开发者以及玩家搭建适合他们的平台。3，支持unciv开发工作。
> 
> ↑很好的初衷，如果你有注意到我这样举例，只是用来回应你一遍遍的重复检举我的一些错误，那么你应该也是时候提升一下自我了，先从言行开始吧。哦，我说的应该说一声，您近期的一次更新的内容在实际使用中看起来很奇怪哦，我并不需要提醒你，因为我已经离开了，翻译并不是由我负责。
> 
> ↑幽默和恶心人是两种东西，前提是你用词准确妥当，因为你是个翻译。
> 
> 以下内容是单独留给heipizhu的，因为您的言行举止，我留给你的其实并不多：
> 
> 对于牵一发动全身的翻译我从一开始就做过，因为每次的修改都是基于我重新进入游戏进行的直接感受，我也很清楚游戏中大部分语句是由早期的版本进行的翻译。 由于最近几次几乎没有翻译，我才在这些天着手研究如何翻译和理解游戏逻辑框架并且找到了github的这个数据库并注册了账号来上传我的更改内容，其中不乏有错误笔画问题以及翻译内容问题，甚至于在一些你看不到的早期版本里，我还格式化错误了。（此处呼应某人的卖惨行为
> 
> 翻译是个兼职，尽管那条翻译在您看来是有些激进，但是在他人的实际游玩体验中确实并不起眼。
> 
> > 作为一个unciv至少25PR的翻译，我可以作证xk730确有翻译，不信去翻以前的PR记录。我会尽可能用中立的话来写这条回复。
> 
> 我并不是在质疑他的贡献，而是在嘲笑他说话时像个锱铢必较的奸商。当然我对我那次失态负责，因为我真的忍不住了，所以用了一些委婉的词语来表达，不过我并不会为此去修改那个时间点的我的情绪，因为那也是我唯一一次最生气的时候。我不会骂人，除非我真的忍不住。
> 
> 是的，我们得尊重每一个人，但是一个人就能影响到整个环境，水至清则无鱼，当我认为一个地方给我带来的快乐和成就感已经远低于时间成本以及获取到的自尊心的时候，我会选择主动离开。
> 
> 我得走了，我再度在这里留下文字，只是为了说教，并不是什么激烈的行为，给每一个人一次机会，我并不会说出来，直到我怒了。

您直到走了还不忘记留下充满偏见的煽动性言论，我深表遗憾。我更遗憾的是，在公共场合，您这段内容却字里行间充满着人身攻击。
1，您推测我与heipizhu先生是现实中的好朋友；我可以明确的回复：No。我与他因翻译工作而认识，您需要思考一下您也是加入翻译工作却为何会与我发生冲突。
2，您这段回信中的用词非常耐人寻味，嗯，您精挑细选的词汇，令人伤心的词汇!
我将为您逐一指点，如果您日后还会以游客方式查阅：
1，，您说我在群内对您“批判”，我很庆幸您没有用“批斗”这个词。然后那一段话给人展现的意义就是：“一个叫xk730的人，自己技术不行，不了解翻译工作，还在那里开批判大会。”  我希望您能够停止对我的污蔑：首先，我没有带头在1300人的群中对您的能力进行指责，其次，我没有使用煽动性语句鼓励成员们辱骂你，我完全是与大家一同分析您翻译内容本身。
2，，您说您贡献了150条，而后又说我拿一个“只是微不足道的‘我爱领袖节’”来对您展开“攻击”。我不知道您有没有注意到您对原本的“我们爱戴领袖日"的修改导致了一众内容发生了变化，我不知道您所说的“微不足道”源自于哪里？？？？？而且我不止于举出这一个值得讨论的地方，我和heipizhu先生各自指出了一些不足，这是显而易见的；他的语气让你感到温柔，我的语气让您感到犀利。您坚定地认为我的目的是人身攻击您。我可以很明确的告诉您，正是因为我将翻译这一工作很重视，我才会指出问题，而不是您说的了解不够，而且我从始至终都没有因为您的多处翻译失误而指责您的能力有问题。
3，，您说我是因为语言能力不好而无法理解您的话，其实这恰恰相反！
很显然您并没有完全看懂我的话——例如其实我已经完成了高考以及我没有说我的家境状况如何。
您说您不攻击我的工作，但又认为我的翻译十分糟糕——既然您已将话如此反复说，那我便明确地告诉您。我不知道您的来历，但将英文翻译为中文这个事情上，不仅仅需要您拥有良好的英文水平，更要拥有出色的中文能力。您在上方回复我的一些内容充满了病句，但我当时没有就此指责您吧？我只是尽力理解您要表达的意思。之后您居然怀疑我的语文存在问题，我可以明确告诉您，我在高中的班级里担任语文课代表。
4，，无论我如何强调，您始终不相信我对您优秀翻译内容的肯定——难道我还要将您优秀的内容逐个指出来然后夸奖一番吗？我想github不是拍马屁的地方！
5，，我也不想多说了，您不断地主观臆断他人的意思，即使是我明确表达了我的态度后您仍然创造另一个我，我由衷地希望在以后的日子里您能够换位思考而不是主观臆断；因为如果我如何劝导解释您的无法听进去，我还不如去继续翻阅文献进行翻译、教别人如何使用github、教大家如何制作mod以及学习Android的开发

最后祝您万事如意，以后的日子里能够不要像过去的三天中那样愤怒。
2022.8.25 中午12：05
xk730

2022-08-28 20:40 UTC, closed without merging